"use client";

import StatusPill from "./StatusPill";
import type { EmployeeFileIssue } from "../../../lib/types";

function issueTitle(issue: EmployeeFileIssue) {
  if (issue.source === "exclusion" && issue.issue_type_label?.trim()) {
    return issue.issue_type_label.trim();
  }
  return issue.issue_type_label?.trim() || issue.name?.trim() || "Issue";
}

/** Hide autogenerated titles that repeat the employee name (shown in the next column). */
function shouldShowIssueName(issue: EmployeeFileIssue, title: string) {
  const name = issue.name?.trim();
  if (!name || name === title) return false;
  const employeeName = issue.employee_name?.trim();
  if (!employeeName) return true;
  if (name.endsWith(`: ${employeeName}`) || name === employeeName) return false;
  if (name.toLowerCase().includes(employeeName.toLowerCase()) && name.includes(":")) {
    return false;
  }
  return true;
}

export default function EmployeeFileIssueCell({
  issue,
  classificationLabel,
}: {
  issue: EmployeeFileIssue;
  classificationLabel: string;
}) {
  const title = issueTitle(issue);
  const showName = shouldShowIssueName(issue, title);

  return (
    <div className="ef-issue-summary">
      <p className="ef-issue-summary__title">{title}</p>
      {showName ? <p className="ef-issue-summary__name">{issue.name}</p> : null}
      <div className="ef-issue-summary__meta">
        <StatusPill label={classificationLabel} tone="attention" />
      </div>
    </div>
  );
}
