{
    "name": "Expense Management",
    "summary": "Claims, requests, advances, payments, petty cash, budgets, and analytics",
    "version": "17.0.7.0.0",
    "category": "Human Resources/Expenses",
    "author": "CleonTime",
    "license": "LGPL-3",
    "depends": ["hr", "mail", "web"],
    "data": [
        "security/hr_expense_management_security.xml",
        "security/ir.model.access.csv",
        "data/hr_claim_sequence.xml",
        "data/hr_claim_data.xml",
        "data/hr_expense_cron.xml",
        "wizard/hr_claim_approval_wizard_views.xml",
        "wizard/hr_claim_reject_wizard_views.xml",
        "wizard/hr_claim_payment_wizard_views.xml",
        "views/hr_claim_category_views.xml",
        "views/hr_claim_type_views.xml",
        "views/hr_claim_window_views.xml",
        "views/hr_claim_views.xml",
        "views/hr_claim_payment_views.xml",
        "views/hr_expense_workflow_views.xml",
        "views/hr_expense_finance_views.xml",
        "views/hr_expense_accounting_views.xml",
        "views/hr_expense_vendor_views.xml",
        "views/hr_expense_budget_views.xml",
        "views/hr_expense_governance_views.xml",
        "views/hr_claim_audit_views.xml",
        "views/hr_claim_dashboard_views.xml",
        "views/hr_claim_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "hr_expense_management/static/src/js/claim_dashboard.js",
            "hr_expense_management/static/src/js/expense_app.js",
            "hr_expense_management/static/src/xml/claim_dashboard.xml",
            "hr_expense_management/static/src/xml/expense_app.xml",
            "hr_expense_management/static/src/scss/claim_dashboard.scss",
            "hr_expense_management/static/src/scss/expense_app.scss",
        ],
    },
    "application": True,
    "installable": True,
}
