from . import hr_document_type
from . import hr_document_folder
from . import hr_document
from . import hr_document_policy_retention
from . import compliance_registration
from . import compliance_engine
from . import compliance_versioning
from . import compliance_work_items
from . import compliance_verification_service
from . import compliance_employee_inbox
from . import compliance_notify
from . import compliance_policy_execution
from . import document_approval
from . import document_acknowledgement
from . import document_version
from . import share_link
from . import hr_employee
from . import res_users
from . import intelligence_profile
from . import intelligence_dataset
from . import intelligence_record
from . import intelligence_index
from . import intelligence_audit
from . import intelligence_conversation
from . import template
from . import template_document
from . import template_assignment
from . import template_submission
from . import template_audit
from . import doc_role_assignment_audit
from . import doc_role_definition
from . import doc_role_service
from . import employee_files_config
from . import employee_file
from . import employee_file_change_log
from . import employee_group
from . import employee_issue
from . import employee_setup
from . import document_relation
from . import employee_esign
from . import employee_files_service
from . import employee_files_role
from . import employee_files_permission
from . import employee_files_role_service
from . import employee_files_role_audit
from . import dms_permission_catalog
from . import organizational_permission_catalog
from . import doc_dms_permission
from . import organizational_files_permission
from . import org_role_template_service
from . import doc_quarantine_file
from . import doc_legal_hold
from . import doc_share_access_log
from . import org_malware_scanner
from . import organizational_approval_request
from . import organizational_approval_service
from . import organizational_retention_service
from . import organizational_openrouter
from . import folder_lock_audit
from . import organizational_library
from . import organizational_policy
from . import compliance_request
from . import compliance_request_content
from . import compliance_request_engine
from . import compliance_request_evaluation
from . import compliance_retention
from . import compliance_retention_engine
from . import compliance_review_schedule
from . import compliance_review_engine
from . import compliance_review_evaluation
from . import organizational_cloud_oauth
