from . import hr_document_type
from . import hr_document_folder
from . import hr_document
from . import hr_document_policy_retention
from . import compliance_registration
from . import compliance_notify
from . import compliance_policy_execution
from . import document_approval
from . import document_acknowledgement
from . import document_version
from . import share_link
from . import hr_employee
from . import res_users
from . import intelligence_profile
from . import intelligence_dataset
from . import intelligence_record
from . import intelligence_index
from . import intelligence_audit
from . import intelligence_conversation
from . import doc_role_assignment_audit
from . import doc_role_definition
from . import doc_role_service
from . import employee_files_config
from . import employee_file
from . import employee_group
from . import employee_issue
from . import employee_setup
from . import document_relation
from . import employee_esign
from . import employee_files_service
