# -*- coding: utf-8 -*-
"""NS-00 default notification events (Global Master Spec)."""

from odoo import api, models

# preference_group maps to user preference email toggles
DEFAULT_NOTIFICATION_EVENTS = [
    # Employee Files
    {
        "event_type": "ef.document_uploaded",
        "name": "Document uploaded",
        "module": "employee_files",
        "who_is_told": "Employee, line manager, HR Admin",
        "recipient_mode": "ef_stakeholders",
        "preference_group": "documents",
        "channel_email": False,
        "required": False,
        "timing": "digest",
        "sequence": 10,
    },
    {
        "event_type": "ef.document_expiring",
        "name": "Document expiring",
        "module": "employee_files",
        "who_is_told": "Employee, line manager, HR Admin",
        "recipient_mode": "ef_stakeholders",
        "preference_group": "documents",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 20,
    },
    {
        "event_type": "ef.document_expired",
        "name": "Document expired",
        "module": "employee_files",
        "who_is_told": "Employee, line manager, HR Admin",
        "recipient_mode": "ef_stakeholders",
        "preference_group": "documents",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 30,
    },
    {
        "event_type": "ef.processing_failed",
        "name": "Processing / ingestion failed",
        "module": "employee_files",
        "who_is_told": "HR Admin",
        "recipient_mode": "hr_admins",
        "preference_group": "documents",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 40,
    },
    {
        "event_type": "ef.upload_needs_approval",
        "name": "Upload needs your approval",
        "module": "employee_files",
        "who_is_told": "Approver",
        "recipient_mode": "approvers",
        "preference_group": "approvals",
        "channel_email": True,
        "required": True,
        "timing": "immediate",
        "sequence": 50,
    },
    {
        "event_type": "ef.upload_approved",
        "name": "Upload approved",
        "module": "employee_files",
        "who_is_told": "Uploader",
        "recipient_mode": "owner",
        "preference_group": "documents",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 60,
    },
    {
        "event_type": "ef.upload_rejected",
        "name": "Upload rejected",
        "module": "employee_files",
        "who_is_told": "Uploader",
        "recipient_mode": "owner",
        "preference_group": "documents",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 70,
    },
    {
        "event_type": "ef.verification_result",
        "name": "Verification result returned",
        "module": "employee_files",
        "who_is_told": "HR Admin",
        "recipient_mode": "hr_admins",
        "preference_group": "documents",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 80,
    },
    {
        "event_type": "ef.setup_failed",
        "name": "Employee File set-up failed",
        "module": "employee_files",
        "who_is_told": "HR Admin",
        "recipient_mode": "hr_admins",
        "preference_group": "documents",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 90,
    },
    {
        "event_type": "ef.integration_failing",
        "name": "Integration failing",
        "module": "employee_files",
        "who_is_told": "HR Admin",
        "recipient_mode": "hr_admins",
        "preference_group": "documents",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 100,
    },
    # Organisational Files
    {
        "event_type": "org.approval_needed",
        "name": "Approval needed",
        "module": "organizational_files",
        "who_is_told": "Approver",
        "recipient_mode": "approvers",
        "preference_group": "approvals",
        "channel_email": True,
        "required": True,
        "timing": "immediate",
        "sequence": 110,
    },
    {
        "event_type": "org.request_decided",
        "name": "Request decided",
        "module": "organizational_files",
        "who_is_told": "Requester",
        "recipient_mode": "actor",
        "preference_group": "organizational",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 120,
    },
    {
        "event_type": "org.access_shared",
        "name": "Access shared with you",
        "module": "organizational_files",
        "who_is_told": "Recipient",
        "recipient_mode": "owner",
        "preference_group": "organizational",
        "channel_email": True,
        "required": False,
        "timing": "digest",
        "sequence": 130,
    },
    {
        "event_type": "org.policy_assigned",
        "name": "Policy assigned to you",
        "module": "organizational_files",
        "who_is_told": "Employee",
        "recipient_mode": "employee_subject",
        "preference_group": "organizational",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 140,
    },
    {
        "event_type": "org.acknowledgement_overdue",
        "name": "Acknowledgement overdue",
        "module": "organizational_files",
        "who_is_told": "Employee",
        "recipient_mode": "employee_subject",
        "preference_group": "organizational",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 150,
    },
    {
        "event_type": "org.external_link_opened",
        "name": "External link opened (owner)",
        "module": "organizational_files",
        "who_is_told": "Document owner",
        "recipient_mode": "owner",
        "preference_group": "organizational",
        "channel_email": True,
        "required": False,
        "timing": "digest",
        "sequence": 160,
    },
    # Templates & Forms
    {
        "event_type": "tf.template_shared",
        "name": "Template shared",
        "module": "templates_forms",
        "who_is_told": "Recipient",
        "recipient_mode": "owner",
        "preference_group": "templates",
        "channel_email": True,
        "required": False,
        "timing": "digest",
        "sequence": 210,
    },
    {
        "event_type": "tf.document_assigned",
        "name": "Document assigned to you",
        "module": "templates_forms",
        "who_is_told": "Assignee",
        "recipient_mode": "owner",
        "preference_group": "templates",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 220,
    },
    {
        "event_type": "tf.request_submitted",
        "name": "Request submitted",
        "module": "templates_forms",
        "who_is_told": "Reviewer",
        "recipient_mode": "approvers",
        "preference_group": "templates",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 230,
    },
    {
        "event_type": "tf.request_approved",
        "name": "Request approved",
        "module": "templates_forms",
        "who_is_told": "Requester",
        "recipient_mode": "actor",
        "preference_group": "templates",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 240,
    },
    {
        "event_type": "tf.request_rejected",
        "name": "Request rejected",
        "module": "templates_forms",
        "who_is_told": "Requester",
        "recipient_mode": "actor",
        "preference_group": "templates",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 250,
    },
    # Signatures
    {
        "event_type": "sig.signature_needed",
        "name": "Your signature is needed",
        "module": "signatures",
        "who_is_told": "Signer",
        "recipient_mode": "owner",
        "preference_group": "signatures",
        "channel_email": True,
        "required": True,
        "timing": "immediate",
        "sequence": 310,
    },
    {
        "event_type": "sig.your_turn",
        "name": "Your turn to sign",
        "module": "signatures",
        "who_is_told": "Signer",
        "recipient_mode": "owner",
        "preference_group": "signatures",
        "channel_email": True,
        "required": True,
        "timing": "immediate",
        "sequence": 320,
    },
    {
        "event_type": "sig.completed",
        "name": "Signature completed",
        "module": "signatures",
        "who_is_told": "Requester",
        "recipient_mode": "actor",
        "preference_group": "signatures",
        "channel_email": True,
        "required": False,
        "timing": "digest",
        "sequence": 330,
    },
    {
        "event_type": "sig.reminder",
        "name": "Signature reminder",
        "module": "signatures",
        "who_is_told": "Signer",
        "recipient_mode": "owner",
        "preference_group": "signatures",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 335,
    },
    {
        "event_type": "sig.declined",
        "name": "Signature declined",
        "module": "signatures",
        "who_is_told": "Requester",
        "recipient_mode": "actor",
        "preference_group": "signatures",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 340,
    },
    {
        "event_type": "sig.overdue",
        "name": "Signature overdue (sender)",
        "module": "signatures",
        "who_is_told": "Requester",
        "recipient_mode": "actor",
        "preference_group": "signatures",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 345,
    },
    {
        "event_type": "sig.expired",
        "name": "Signature expired",
        "module": "signatures",
        "who_is_told": "Requester",
        "recipient_mode": "actor",
        "preference_group": "signatures",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 350,
    },
    {
        "event_type": "sig.cancelled",
        "name": "Signature cancelled",
        "module": "signatures",
        "who_is_told": "Signer",
        "recipient_mode": "owner",
        "preference_group": "signatures",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 355,
    },
    # Approvals
    {
        "event_type": "appr.approval_needed",
        "name": "Approval needed",
        "module": "approvals",
        "who_is_told": "Approver",
        "recipient_mode": "approvers",
        "preference_group": "approvals",
        "channel_email": True,
        "required": True,
        "timing": "immediate",
        "sequence": 410,
    },
    {
        "event_type": "appr.delegate_assigned",
        "name": "Delegate assigned",
        "module": "approvals",
        "who_is_told": "Delegate",
        "recipient_mode": "owner",
        "preference_group": "approvals",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 420,
    },
    {
        "event_type": "appr.reminder",
        "name": "Approval reminder",
        "module": "approvals",
        "who_is_told": "Approver",
        "recipient_mode": "approvers",
        "preference_group": "approvals",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 415,
    },
    {
        "event_type": "appr.past_deadline",
        "name": "Past deadline (fallback)",
        "module": "approvals",
        "who_is_told": "Approver",
        "recipient_mode": "approvers",
        "preference_group": "approvals",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 425,
    },
    # Alerts
    {
        "event_type": "alert.critical_in_scope",
        "name": "Critical alert in your scope",
        "module": "alerts",
        "who_is_told": "Assigned users",
        "recipient_mode": "custom_users",
        "preference_group": "alerts",
        "channel_email": True,
        "required": False,
        "timing": "critical_immediate",
        "sequence": 510,
    },
    {
        "event_type": "alert.assigned_to_you",
        "name": "Alert assigned to you",
        "module": "alerts",
        "who_is_told": "Assignee",
        "recipient_mode": "owner",
        "preference_group": "alerts",
        "channel_email": True,
        "required": False,
        "timing": "critical_immediate",
        "sequence": 520,
    },
    # Document Intelligence
    {
        "event_type": "di.job_completed",
        "name": "Job completed",
        "module": "document_intelligence",
        "who_is_told": "Requester",
        "recipient_mode": "actor",
        "preference_group": "platform",
        "channel_email": True,
        "required": False,
        "timing": "digest",
        "sequence": 610,
    },
    {
        "event_type": "di.job_failed",
        "name": "Job failed",
        "module": "document_intelligence",
        "who_is_told": "Requester",
        "recipient_mode": "actor",
        "preference_group": "platform",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 620,
    },
    {
        "event_type": "di.records_to_review",
        "name": "Records to review assigned to you",
        "module": "document_intelligence",
        "who_is_told": "Reviewer",
        "recipient_mode": "owner",
        "preference_group": "platform",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 630,
    },
    # Platform
    {
        "event_type": "platform.export_ready",
        "name": "Export ready",
        "module": "platform",
        "who_is_told": "Requester",
        "recipient_mode": "actor",
        "preference_group": "platform",
        "channel_email": True,
        "required": False,
        "timing": "digest",
        "sequence": 710,
    },
    {
        "event_type": "platform.report_delivered",
        "name": "Scheduled report delivered",
        "module": "platform",
        "who_is_told": "Recipient",
        "recipient_mode": "owner",
        "preference_group": "platform",
        "channel_email": True,
        "required": False,
        "timing": "digest",
        "sequence": 720,
    },
    {
        "event_type": "platform.legal_hold_placed",
        "name": "Legal hold placed on a document you own",
        "module": "platform",
        "who_is_told": "Document owner",
        "recipient_mode": "owner",
        "preference_group": "platform",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 730,
    },
    # Compliance (read-only in settings UI)
    {
        "event_type": "compliance.policy_reminder",
        "name": "Defined per policy in Compliance",
        "module": "compliance",
        "who_is_told": "Employee / HR (per policy)",
        "recipient_mode": "custom_users",
        "preference_group": "compliance",
        "channel_email": True,
        "required": False,
        "timing": "immediate",
        "sequence": 810,
        "compliance_read_only": True,
    },
]

PREFERENCE_GROUPS = [
    ("signatures", "Signatures", True),
    ("documents", "Documents", False),
    ("approvals", "Approvals", True),
    ("organizational", "Organisational files", False),
    ("templates", "Templates & forms", False),
    ("compliance", "Compliance", False),
    ("alerts", "Triggers & alerts", False),
    ("platform", "Platform", False),
]


class DocNotificationCatalogService(models.AbstractModel):
    _name = "doc.notification.catalog.service"
    _description = "Seed NS-00 notification rules"

    @api.model
    def _remove_duplicate_notification_rules(self):
        """Keep the oldest row per (company, event_type); drop accidental duplicates."""
        Rule = self.env["doc.notification.rule"].sudo()
        seen = {}
        duplicate_ids = []
        for rule in Rule.search([], order="company_id, event_type, id"):
            key = (rule.company_id.id, rule.event_type)
            if key in seen:
                duplicate_ids.append(rule.id)
            else:
                seen[key] = rule.id
        if duplicate_ids:
            Rule.browse(duplicate_ids).unlink()

    @api.model
    def ensure_default_notification_rules(self):
        Rule = self.env["doc.notification.rule"].sudo()
        self._remove_duplicate_notification_rules()
        for company in self.env["res.company"].search([]):
            for spec in DEFAULT_NOTIFICATION_EVENTS:
                domain = [
                    ("event_type", "=", spec["event_type"]),
                    ("company_id", "=", company.id),
                ]
                existing = Rule.search(domain, limit=1)
                if existing:
                    continue
                Rule.create(
                    {
                        "name": spec["name"],
                        "event_type": spec["event_type"],
                        "event_label": spec["name"],
                        "module": spec["module"],
                        "who_is_told": spec["who_is_told"],
                        "recipient_mode": spec["recipient_mode"],
                        "preference_group": spec["preference_group"],
                        "channel_in_app": True,
                        "channel_email": spec.get("channel_email", False),
                        "active": True,
                        "required": spec.get("required", False),
                        "timing": spec.get("timing", "immediate"),
                        "sequence": spec.get("sequence", 10),
                        "compliance_read_only": spec.get(
                            "compliance_read_only", False
                        ),
                        "company_id": company.id,
                    }
                )
