import type {
  CompliancePolicy,
  DocDocument,
  DocFolder,
  DocumentType,
  DashboardStats,
  ShareLink,
  User,
} from "./types";

export const TEST_USER: User = {
  id: 12,
  name: "Amaka Okafor",
  email: "amaka.okafor@cleonhr.test",
  company_id: 1,
  company_name: "CleonHR Nigeria Ltd.",
  tz: "Africa/Lagos",
};

export const TEST_FOLDERS: DocFolder[] = [
  {
    id: 1,
    folder_name: "Employee Files",
    description: "Confidential employee records and supporting documents.",
    folder_type: "employee",
    owner_id: TEST_USER.id,
    owner_name: TEST_USER.name,
    document_count: 3,
    last_modified: "2026-08-28 10:15:00",
    access_scope: "all_staff",
    is_locked: false,
    color: 4,
    employee_ids: [12],
  },
  {
    id: 2,
    folder_name: "Company Policies",
    description: "Current HR, compliance, and workplace policies.",
    folder_type: "organizational",
    owner_id: TEST_USER.id,
    owner_name: TEST_USER.name,
    document_count: 2,
    last_modified: "2026-08-22 15:40:00",
    access_scope: "all_staff",
    is_locked: false,
    color: 7,
  },
  {
    id: 3,
    folder_name: "Finance & Audit",
    description: "Finance evidence and audit-ready supporting files.",
    folder_type: "organizational",
    owner_id: TEST_USER.id,
    owner_name: TEST_USER.name,
    document_count: 2,
    last_modified: "2026-08-19 09:05:00",
    access_scope: "role",
    is_locked: true,
    color: 2,
  },
];

export const TEST_DOCUMENT_TYPES: DocumentType[] = [
  { id: 1, name: "Identity Document", category: "identity", is_mandatory_default: true, default_retention_years: 7, active: true },
  { id: 2, name: "Employment Contract", category: "employment", is_mandatory_default: true, default_retention_years: 7, active: true },
  { id: 3, name: "HR Policy", category: "hr", is_mandatory_default: false, default_retention_years: 5, active: true },
  { id: 4, name: "Financial Record", category: "finance", is_mandatory_default: false, default_retention_years: 10, active: true },
];

export const TEST_POLICY_TYPES = [
  { id: 1, name: "Document Requirement", code: "document_requirement" },
  { id: 2, name: "Renewable Document", code: "renewable_document" },
  { id: 3, name: "Compliance Request", code: "compliance_request" },
  { id: 4, name: "Retention", code: "retention" },
];

export const TEST_COMPLIANCE_TARGETS = {
  employees: [{ id: 12, name: "Amaka Okafor", job_title: "HR Manager", department: "People Operations", department_id: 1, grade: "GL-6", grade_id: 1, work_email: "amaka.okafor@cleonhr.test", work_phone: "+234 800 000 0000", location: "Lagos" }],
  departments: [
    { id: 1, name: "People Operations" },
    { id: 2, name: "Customer Success" },
    { id: 3, name: "Finance" },
    { id: 4, name: "Technology" },
  ],
  grades: [{ id: 1, name: "GL-6" }, { id: 2, name: "GL-7" }, { id: 3, name: "GL-8" }],
};

export const TEST_EXCEPTIONS = [{ id: 1, employee_id: 12, employee: "Amaka Okafor", policy_id: 2, policy: "Mandatory Employment Contract", reason: "Contract renewal is in progress.", valid_until: "2026-10-31", status: "pending" }];
export const TEST_EVALUATIONS = [{ id: 1, policy_id: 1, policy: "Annual Identity Verification", employee_id: 12, employee: "Amaka Okafor", score: 100, status: "compliant", complete_count: 1, missing_count: 0, evaluated_at: "2026-09-04 12:00:00" }];

export const TEST_DOCUMENTS: DocDocument[] = [
  {
    id: 101,
    name: "Amaka Okafor - International Passport",
    description: "Identity verification document for employee onboarding.",
    folder_id: 1,
    folder_name: "Employee Files",
    employee_id: 12,
    employee_name: "Amaka Okafor",
    document_type_id: 1,
    document_type: "Identity Document",
    state: "approved",
    approval_state: "approved",
    ocr_state: "completed",
    has_expiry: true,
    expiry_date: "2027-04-18",
    mime_type: "application/pdf",
    file_size: 2480000,
    attachment_id: 501,
    created_at: "2026-01-12 08:30:00",
    write_date: "2026-01-13 11:20:00",
  },
  {
    id: 102,
    name: "Amaka Okafor - Employment Contract",
    description: "Signed employment agreement and terms of service.",
    folder_id: 1,
    folder_name: "Employee Files",
    employee_id: 12,
    employee_name: "Amaka Okafor",
    document_type_id: 2,
    document_type: "Employment Contract",
    state: "approved",
    approval_state: "approved",
    ocr_state: "completed",
    has_expiry: false,
    expiry_date: null,
    mime_type: "application/pdf",
    file_size: 1850000,
    attachment_id: 502,
    created_at: "2026-01-10 14:10:00",
    write_date: "2026-01-10 16:45:00",
  },
  {
    id: 103,
    name: "Emergency Contact Form",
    description: "Employee emergency contact details awaiting HR review.",
    folder_id: 1,
    folder_name: "Employee Files",
    employee_id: 12,
    employee_name: "Amaka Okafor",
    document_type_id: 2,
    document_type: "Employment Contract",
    state: "processing",
    approval_state: "pending",
    ocr_state: "processing",
    has_expiry: false,
    expiry_date: null,
    mime_type: "image/jpeg",
    file_size: 920000,
    attachment_id: 503,
    created_at: "2026-08-28 10:15:00",
    write_date: "2026-08-28 10:16:00",
  },
  {
    id: 201,
    name: "Code of Conduct 2026",
    description: "Standards of behaviour, reporting, and disciplinary process.",
    folder_id: 2,
    folder_name: "Company Policies",
    employee_id: null,
    employee_name: "N/A",
    document_type_id: 3,
    document_type: "HR Policy",
    state: "approved",
    approval_state: "not_required",
    ocr_state: "completed",
    has_expiry: true,
    expiry_date: "2027-01-01",
    mime_type: "application/pdf",
    file_size: 3260000,
    attachment_id: 504,
    created_at: "2026-01-02 09:00:00",
    write_date: "2026-08-22 15:40:00",
  },
  {
    id: 202,
    name: "Information Security Policy",
    description: "Access control, device security, and incident response policy.",
    folder_id: 2,
    folder_name: "Company Policies",
    employee_id: null,
    employee_name: "N/A",
    document_type_id: 3,
    document_type: "HR Policy",
    state: "draft",
    approval_state: "pending",
    ocr_state: "pending",
    has_expiry: true,
    expiry_date: "2026-10-15",
    mime_type: "application/pdf",
    file_size: 4100000,
    attachment_id: 505,
    created_at: "2026-08-18 12:00:00",
    write_date: "2026-08-20 13:10:00",
  },
  {
    id: 301,
    name: "Q2 Expense Audit Evidence",
    description: "Supporting evidence pack for the second-quarter expense audit.",
    folder_id: 3,
    folder_name: "Finance & Audit",
    employee_id: null,
    employee_name: "N/A",
    document_type_id: 4,
    document_type: "Financial Record",
    state: "approved",
    approval_state: "approved",
    ocr_state: "completed",
    has_expiry: false,
    expiry_date: null,
    mime_type: "application/zip",
    file_size: 18400000,
    attachment_id: 506,
    created_at: "2026-07-05 16:20:00",
    write_date: "2026-07-06 09:25:00",
  },
  {
    id: 302,
    name: "Vendor Due Diligence Checklist",
    description: "Review checklist for a new payroll services vendor.",
    folder_id: 3,
    folder_name: "Finance & Audit",
    employee_id: null,
    employee_name: "N/A",
    document_type_id: 4,
    document_type: "Financial Record",
    state: "rejected",
    approval_state: "rejected",
    ocr_state: "failed",
    has_expiry: false,
    expiry_date: null,
    mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    file_size: 760000,
    attachment_id: 507,
    created_at: "2026-08-17 09:45:00",
    write_date: "2026-08-19 09:05:00",
  },
];

export const TEST_STATS: DashboardStats = {
  total_documents: TEST_DOCUMENTS.length,
  total_folders: TEST_FOLDERS.length,
  total_policies: 4,
  total_exceptions: 2,
  expiring_documents: 2,
  pending_approvals: 2,
};

export const TEST_POLICIES: CompliancePolicy[] = [
  {
    id: 1,
    name: "Annual Identity Verification",
    description: "Every active employee must have a current identity document.",
    policy_type_id: 1,
    policy_type: "Document Completeness",
    document_type_ids: [1],
    schedule: "yearly",
    custom_schedule_days: 365,
    applies_to: "all_staff",
    department_ids: [],
    grade_ids: [],
    employee_ids: [],
    minimum_documents: 1,
    grace_period_days: 30,
    effective_date: "2026-01-01",
    active: true,
  },
  {
    id: 2,
    name: "Mandatory Employment Contract",
    description: "All employees must have an approved employment contract on file.",
    policy_type_id: 1,
    policy_type: "Document Completeness",
    document_type_ids: [2],
    schedule: "manual",
    custom_schedule_days: 30,
    applies_to: "all_staff",
    department_ids: [],
    grade_ids: [],
    employee_ids: [],
    minimum_documents: 1,
    grace_period_days: 14,
    effective_date: "2026-01-01",
    active: true,
  },
];

export const TEST_SHARE_LINKS: ShareLink[] = [
  {
    id: 1,
    token: "test-code-of-conduct-2026",
    permission: "viewer",
    expiry_date: "2026-12-31 23:59:59",
    access_count: 18,
    active: true,
    allow_download: false,
  },
];
