{
    'name': 'CLEONHR Leave',
    'version': '17.0.1.0.0',
    'category': 'CleonHR-HR ADMIN',
    'depends': ['hr_holidays', 'web', 'hr_company_calendar', 'hr_administration', 'hr_employee'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'views/dashboard_action.xml',
        'views/leave_base.xml',
        'views/menu.xml',
        'views/hr_leave_type_views.xml',
        'views/leave_balance_views.xml',
        'views/leave_report_views.xml',
        'views/leave_audit_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'hr_leave_dashboard/static/src/components/setup_wizard/setup_wizard.js',
            'hr_leave_dashboard/static/src/components/setup_wizard/setup_wizard.xml',
            'hr_leave_dashboard/static/src/js/dashboard.js',
            'hr_leave_dashboard/static/src/components/dashboard_router/dashboard_router.js',
            'hr_leave_dashboard/static/src/components/dashboard_router/dashboard_router.xml',
            'hr_leave_dashboard/static/src/css/dashboard.css',
            'hr_leave_dashboard/static/src/xml/dashboard.xml',
            'hr_leave_dashboard/static/src/js/leave_requests.js',
            'hr_leave_dashboard/static/src/css/leave_requests.css',
            'hr_leave_dashboard/static/src/xml/leave_requests.xml',
            'hr_leave_dashboard/static/src/components/calendar_sidebar.xml',
            'hr_leave_dashboard/static/src/components/calendar_sidebar.js',
            'hr_leave_dashboard/static/src/components/leave_request_detail/leave_request_detail.js',
            'hr_leave_dashboard/static/src/components/leave_request_detail/leave_request_detail.xml',
            'hr_leave_dashboard/static/src/components/leave_request_detail/leave_request_detail.css',
            'hr_leave_dashboard/static/src/js/leave_calendar.js',
            'hr_leave_dashboard/static/src/xml/leave_calendar.xml',
            'hr_leave_dashboard/static/src/css/leave_calendar.css',
            'hr_leave_dashboard/static/src/components/leave_types/leave_types_page.js',
            'hr_leave_dashboard/static/src/components/leave_types/leave_type_detail_drawer.js',
            'hr_leave_dashboard/static/src/components/leave_types/leave_type_form_modal.js',
            'hr_leave_dashboard/static/src/components/leave_types/leave_types.xml',
            'hr_leave_dashboard/static/src/css/leave_types.css',
            'hr_leave_dashboard/static/src/components/leave_balances/leave_balances.js',
            'hr_leave_dashboard/static/src/components/leave_balances/leave_balances.xml',
            'hr_leave_dashboard/static/src/components/leave_balances/leave_balances.css',
            'hr_leave_dashboard/static/src/components/leave_reports/leave_reports.js',
            'hr_leave_dashboard/static/src/components/leave_reports/leave_reports.xml',
            'hr_leave_dashboard/static/src/components/leave_reports/leave_reports.css',
            'hr_leave_dashboard/static/src/components/leave_audit/leave_audit.js',
            'hr_leave_dashboard/static/src/components/leave_audit/leave_audit.xml',
            'hr_leave_dashboard/static/src/components/leave_audit/leave_audit.css',
            'hr_leave_dashboard/static/src/components/employee_dashboard/employee_dashboard.js',
            'hr_leave_dashboard/static/src/components/employee_dashboard/employee_dashboard.xml',
            'hr_leave_dashboard/static/src/components/employee_dashboard/employee_dashboard.css',
            'hr_leave_dashboard/static/src/components/employee_dashboard/employee_dashboard_alignment.css',
            'hr_leave_dashboard/static/src/components/employee_request_modal/employee_request_modal.js',
            'hr_leave_dashboard/static/src/components/employee_request_modal/employee_request_modal.xml',
            'hr_leave_dashboard/static/src/components/employee_request_modal/employee_request_modal.css',
            'hr_leave_dashboard/static/src/components/my_leave_requests/my_leave_requests.js',
            'hr_leave_dashboard/static/src/components/my_leave_requests/my_leave_requests.xml',
            'hr_leave_dashboard/static/src/components/my_leave_requests/my_leave_requests.css',
            'hr_leave_dashboard/static/src/components/get_started/get_started.js',
            'hr_leave_dashboard/static/src/components/get_started/get_started.xml',
            'hr_leave_dashboard/static/src/components/get_started/get_started.css',
        ],
    },
    'license': 'LGPL-3',
}
